global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8001']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'nvidia-smi'
    static_configs:
      - targets: ['localhost:9445']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093